import 'package:flutter/material.dart';
import 'dart:io';
import 'package:provider/provider.dart';
import 'package:stylens_app/models/remote_image.dart';
import 'package:stylens_app/widgets/error_display.dart';
import '../widgets/message_bubble.dart';
import '../widgets/message_input.dart';
import '../models/chat_message.dart';
import '../core/managers/style_analysis_session_manager.dart';

// If users land on this page from uploading an outfit image, we pass the image file here.
// If users land on this page from the history page, we would fetch the session data instead.

class StyleAnalysisPage extends StatefulWidget {
  final File? outfitImageFile;
  final RemoteImage? remoteImage;
  final String? sessionId;

  const StyleAnalysisPage({
    super.key,
    this.outfitImageFile,
    this.remoteImage,
    this.sessionId,
  }) : assert(
         (outfitImageFile != null && sessionId == null) ||
             (outfitImageFile == null && sessionId != null),
         'Either outfitImageFile or sessionId must be provided, but not both.',
       );

  @override
  State<StyleAnalysisPage> createState() => _StyleAnalysisPageState();
}

class _StyleAnalysisPageState extends State<StyleAnalysisPage> {
  final TextEditingController _messageController = TextEditingController();
  final List<ChatMessage> _messages = [];

  // Add flag to track if session has been created remotely
  bool _isSessionCreatedRemotely = false;
  String? _localSessionId; // Store the session ID once created

  @override
  void initState() {
    super.initState();

    if (widget.sessionId != null) {
      // Load existing session data - already created remotely
      _isSessionCreatedRemotely = true;
      _localSessionId = widget.sessionId;
      WidgetsBinding.instance.addPostFrameCallback((_) {
        _loadSessionData();
      });
      return;
    } else if (widget.outfitImageFile != null) {
      // Start new session with uploaded image - NOT yet created remotely
      _isSessionCreatedRemotely = false;
      _addInitialOutfitMessage();
      _addStyleAnalyzerBotMessage(
        "Looking great! 🔥 What's the occasion for this outfit?",
      );
    }
  }

  Future<void> _loadSessionData() async {
    try {
      final sessionManager = context.read<StyleAnalysisSessionManager>();
      await sessionManager.fetchSessionMessages(widget.sessionId!);
    } catch (e) {
      // Error is already set in the session manager
      print('Error loading session: $e');
    }
  }

  void _addInitialOutfitMessage() {
    print('Adding initial outfit message: ${widget.outfitImageFile}');
    setState(() {
      _messages.add(
        ChatMessage(
          isUser: true,
          imageFile: widget.outfitImageFile,
          remoteImage: widget.remoteImage,
          timestamp: DateTime.now(),
        ),
      );
    });
  }

  // Should be autogenerated by LLM based on subsequent prompt
  void _addStyleAnalyzerBotMessage(String text) {
    setState(() {
      _messages.add(
        ChatMessage(isUser: false, text: text, timestamp: DateTime.now()),
      );
    });
  }

  void _sendMessage() async {
    if (_messageController.text.trim().isEmpty) return;

    final userMessage = _messageController.text.trim();

    // If session hasn't been created remotely, create it now
    if (!_isSessionCreatedRemotely && widget.outfitImageFile != null) {
      final sessionManager = context.read<StyleAnalysisSessionManager>();

      // Add user message to local state
      setState(() {
        _messages.add(
          ChatMessage(
            isUser: true,
            text: userMessage,
            timestamp: DateTime.now(),
          ),
        );
      });

      _messageController.clear();

      // Create session remotely with the outfit image
      final sessionId = await sessionManager.createSession(messages: _messages);

      if (sessionId != null) {
        _isSessionCreatedRemotely = true;
        _localSessionId = sessionId;

        // TODO: Get AI response from backend
        // Future.delayed(Duration(seconds: 1), () {
        //   _addStyleAnalyzerBotMessage(
        //     "Thanks for sharing! I can see this is perfect for $userMessage. Let me analyze your style...",
        //   );
        // });
      } else {
        // Handle error - show snackbar or error message
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to create session. Please try again.'),
            ),
          );
        }
      }
      return;
    }

    setState(() {
      _messages.add(
        ChatMessage(isUser: true, text: userMessage, timestamp: DateTime.now()),
      );
    });

    _messageController.clear();

    // TODO: Add AI response logic here
    // Future.delayed(Duration(seconds: 1), () {
    //   _addStyleAnalyzerBotMessage(
    //     "Thanks for sharing! I can see this is perfect for $userMessage. Let me analyze your style...",
    //   );
    // });
  }

  // This class will contain methods and properties related to style analysis.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            Text(
              'GoStylens',
              style: TextStyle(
                fontFamily: 'ClashDisplay',
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSecondary,
              ),
            ),
          ],
        ),
        titleSpacing: 0,
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        leading: IconButton(
          icon: Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Consumer<StyleAnalysisSessionManager>(
        builder: (context, sessionManager, child) {
          if (sessionManager.isLoadingMessages) {
            return Center(child: CircularProgressIndicator());
          }

          // Show error UI if there's an error
          if (sessionManager.error != null && widget.sessionId != null) {
            return ErrorDisplay(
              title: 'Failed to load session',
              message: sessionManager.error!,
              onRetry: _loadSessionData,
            );
          }

          // Use session manager's messages if loading existing session,
          // otherwise use local _messages for new sessions
          final messages = widget.sessionId != null
              ? sessionManager.selectedSessionMessages
              : _messages;

          return Column(
            children: [
              Expanded(
                child: ListView.builder(
                  padding: EdgeInsets.all(16),
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    return MessageBubble(message: messages[index]);
                  },
                ),
              ),
              MessageInput(
                messageController: _messageController,
                onSendMessage: _sendMessage,
              ),
            ],
          );
        },
      ),
    );
  }

  @override
  void dispose() {
    _messageController.dispose();
    super.dispose();
  }
}
