name: gostylens
description: "Your personal stylist on the go."
publish_to: "none"
version: 0.2.7+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.3
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.6.0
  dio: ^5.11.0
  supabase_flutter: ^2.17.2
  google_sign_in: ^7.2.0
  font_awesome_flutter: ^11.0.0
  flutter_native_splash: ^2.4.8
  flutter_dotenv: ^6.0.1
  purchases_flutter: ^9.16.1
  lottie: ^3.5.1
  intl: ^0.20.3
  url_launcher: ^6.3.2
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.7
  pinput: ^6.0.2
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.1
  posthog_flutter: ^5.36.6
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  path_provider: ^2.1.6
  flutter_markdown: ^0.7.7
  shared_preferences: ^2.5.5
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  geolocator: ^13.0.4
  app_links: ^7.2.1
  go_router: ^17.5.0
  flutter_blurhash: ^0.8.2
  blurhash_dart: ^1.2.1
  image: ^4.9.2
  skeletonizer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  fake_async: ^1.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.otf
        - asset: assets/fonts/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Bold.otf
          weight: 700
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-Black.otf
          weight: 900
  assets:
    - .env.development
    - .env.production
    - .env.staging
    - assets/icon/
    - assets/animations/
    - assets/imgs/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"