abstract class UxMessages {
  // --- Global Loader ---
  static const String uploadOutfitLoader =
      'Your stylist is getting ready to analyze your outfit...';

  // --- Message Input ---
  static const String styleAnalysisChatInputPlaceholder =
      'Message your stylist';
  static const String messagePlaceholderDefault = 'Type your message...';

  // --- Errors ---
  static const String sessionCreateFailed =
      'Unable to initiate styling session. Please try again.';
  static const String uploadFailed =
      'Failed to upload image. Please try again.';
  static const String userNotFound = 'User not found or error occurred';
  static const String streamingFailed =
      'Unable to get response from stylist. Please try again.';

  // --- Snackbar ---
  static const String dismiss = 'Dismiss';

  // --- Autogenerated chat message ---
  static const String initialOutfitPromptTextAugmentation =
      'What do you think about my outfit?';
  static const String initialStylistReplyWithImage =
      "Looking great! 🔥 What's the occasion for this outfit?";
  static const String initialStylistReplyWithoutImage1 =
      "Hey! I'm your stylist. Let's get started on your vibe for today.";
  static const String initialStylistReplyWithoutImage2 =
      "Whenever you're ready, share your outfit and I'll jump right in with some tips!";

  // --- Location permission ---
  static const String locationExplainerTitle = 'Weather-aware styling';
  static const String locationExplainerBody =
      'Allow location access so your stylist can factor in your local weather when suggesting outfits.';
  static const String locationExplainerAllow = 'Allow';
  static const String locationExplainerNotNow = 'Not now';
  static const String locationDeniedForeverTitle = 'Location access needed';
  static const String locationDeniedForeverBody =
      'Location is turned off for GoStylens. Enable it in Settings to get weather-aware styling tips.';
  static const String locationOpenSettings = 'Open Settings';
  static const String locationServicesDisabled =
      'Location services are turned off on this device.';

  // --- Marketing email consent ---
  // Shared by onboarding + post-activation re-ask sheet — keep copy valid in both contexts.
  static const String marketingEmailTitle = 'Want style tips by email?';
  static const String marketingEmailBody =
      'Occasional fit-check nudges, nothing spammy. Change anytime in Profile.';
  static const String marketingEmailYes = 'Yes, email me';
  static const String marketingEmailNotNow = 'Not now';
  static const String marketingEmailUpdateFailed =
      'Couldn\'t update email preference. Try again.';
}
