abstract class UxMessages {
  // --- Global Loader ---
  static const String uploadOutfitLoader =
      'Your stylist is getting ready to analyze your outfit...';

  // --- Message Input ---
  static const String styleAnalysisChatInputPlaceholder =
      'Message your stylist';
  static const String messagePlaceholderDefault = 'Type your message...';

  // --- Errors ---
  static const String sessionCreateFailed =
      'Unable to initiate styling session. Please try again.';
  static const String uploadFailed =
      'Failed to upload image. Please try again.';
  static const String userNotFound = 'User not found or error occurred';

  // --- Snackbar ---
  static const String dismiss = 'Dismiss';

  // --- Autogenerated chat message ---
  static const String initialOutfitPromptTextAugmentation =
      'What do you think about my outfit?';
  static const String initialStylistReplyWithImage =
      "Looking great! 🔥 What's the occasion for this outfit?";
  static const String initialStylistReplyWithoutImage1 =
      "Hey! I'm your stylist. Let's get started on your vibe for today.";
  static const String initialStylistReplyWithoutImage2 =
      "Whenever you're ready, share your outfit and I'll jump right in with some tips!";
}
