name: Deploy iOS to Development
on:
    workflow_dispatch:
        inputs:
            version:
                description: "App Version (e.g. 1.0.0)"
                required: true
                default: "1.0.0"
            build:
                description: "Build Number (e.g. 42)"
                required: true
                default: "1"
            groups:
                description: "Firebase Tester Groups"
                required: true
                default: "gostylens-vanguards"
            release_notes:
                description: "Release Notes"
                required: true
                default: "Initial iOS Release"
            testers:
                description: "Firebase Testers (optional)"
                required: false
                default: ""
            env:
                description: "Environment (staging or production)"
                required: true
                default: "staging"

permissions:
  contents: read

jobs:
    deployIOSDevelopment:
        runs-on: macos-latest
        env:
            APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
            FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

        steps:

            # v4.2.2
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

            # v2.18.0
            - name: Flutter setup
              uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
              with:
                channel: "stable"
                cache: true
              id: flutter

            - name: Accept Xcode License
              run: sudo xcodebuild -license accept

            - name: Setup Environment Files
              env:
                ENV_STAGING_FILE: ${{ secrets.ENV_STAGING_FILE }}
                STG_IOS_GOOGLE_SERVICE_INFO: ${{ secrets.STG_IOS_GOOGLE_SERVICE_INFO }}
              run: |
                echo "$ENV_STAGING_FILE" > .env.staging
                echo "$STG_IOS_GOOGLE_SERVICE_INFO" > ios/Runner/GoogleService-Info.plist
                touch .env.development
                touch .env.production

            - name: Get packages
              run: flutter pub get
              
            - name: Generate Xcode Config
              run: flutter build ios --config-only
              
            # v4.0.2
            - name: Cache Pods
              uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
              with:
                path: ios/Pods
                key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
                restore-keys: |
                  ${{ runner.os }}-pods-

            - name: Install CocoaPods
              run: |
                cd ios
                pod install
              
            # v1.180.0
            - name: Setup Fastlane
              uses: ruby/setup-ruby@26543b599723220f18833989c9e88d669a08e562
              with:
                ruby-version: "3.3"
                bundler-cache: true
                working-directory: ios

            - name: Set up Firebase authentication
              run: echo "${FIREBASE_SERVICE_ACCOUNT}" > ./ios/fastlane/service-account.json

            - name: Build and Deploy to Firebase App Distribution
              env:
                MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
                MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
                VERSION: ${{ github.event.inputs.version }}
                BUILD_NUMBER: ${{ github.event.inputs.build }}
                RELEASE_NOTES: ${{ github.event.inputs.release_notes }}
                GROUPS: ${{ github.event.inputs.groups }}
                TESTERS: ${{ github.event.inputs.testers }}
                ENV: ${{ github.event.inputs.env }}
              run: |
                cd ./ios
                bundle exec fastlane ios development \
                  version:"$VERSION" \
                  build_number:"$BUILD_NUMBER" \
                  release_notes:"$RELEASE_NOTES" \
                  groups:"$GROUPS" \
                  testers:"$TESTERS" \
                  env:"$ENV"