name: Flutter CI Tests
on:
    push:
      branches: 
        - main
    pull_request:
      branches: 
        - main

permissions:
  contents: read

jobs:
    test:
        name: Run flutter tests
        runs-on: ubuntu-latest

        steps:
            # v4.2.2
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            # v2.18.0
            - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
              with:
                channel: "stable"
                cache: true
            - run: flutter --version
            - name: Get packages
              run: flutter pub get

            - name: Run tests
              run: |
                if [ -d "test" ]; then
                  flutter test
                else
                  echo "No test directory found, skipping tests."
                fi
    